## created by @opbi/ncm
---
component:
  type: package
  name: toolchain
  description: the swiss knife to lift business logic to be production ready
  keywords: decorators, functional, observability
  private: false
package:
  environment: node
  npmScope: opbi
owner:
  type: organisation
  github: opbi
  team: ''
  name: ''
  email: zhenyu.lin@opbi.org
